add(Header.jsx)
nickxgrom/typing-western pull request #1
Opened 2023-07-08 17:43 UTC by nickxgrom

Icon component (shared)
Brand component
Menu component
Account component
eslint rules: props, brackets

2023-07-08 18:12 UTC, cogniocode requested changes

2023-07-08 18:12 UTC, cogniocode commented on src/components/header/menu/Menu.jsx
> +                <button className={`${classes.menuButton} ${classes.disabled}`}>
Как-то странно. Вроде как можно просто объявить селектор `.menuButton .disabled` и `disabled` написать просто без импорта.

2023-07-08 18:12 UTC, cogniocode commented on src/components/shared/icon/Icon.jsx
> +            className={`${classes.icon} ${className}`}
Для склеивания классов есть библиотека `classnames`.

2023-07-08 18:12 UTC, cogniocode commented on tailwind.config.js
> +        colors: {
Дополнения к стандартной теме лучше писать в `extend` потому-что иначе ты перезаписываешь все цвета Tailwind. Они становятся недоступны.

2023-07-09 15:18 UTC, nickxgrom commented on src/components/header/menu/Menu.jsx
> +                <button className={`${classes.menuButton} ${classes.disabled}`}>
![image](https://github.com/nickxgrom/typing-western/assets/52834219/239eb7d0-786f-42c6-9bfa-10ce93ccf00c)
Не резолвится обычный `disabled` с тем что объявлен внутри `menuButton`

2023-07-09 15:20 UTC, merged